	|1-3.~  God, as the unmoved source of movement, is the
central conception of the Aristotelian theology.  Wallace, 39,
46.  

	God ^penetrates~ into the essential nature of a thing, and
^is reflected~ ("regloweth"), more or less, in its concrete
being.  ^Epist. ad Can. Grand.~, 23; ^Conv.~ iii. 14: 29-50.

	|13.~  Apollo = the Sun = God.  ^Conv.~ iii. 12: 52-54, and
^passim.~

	|16.~  ^One peak.~  Hitherto the inspiration of the Muses has
sufficed (^cf. Inf.~ ii. 7, ^Purg.~ i. 8), but now the diviner aid of
"Apollo" must be invoked as well.  It is not easy to trace the origin
of Dante's (erroneous) belief that one peak of Parnassus was sacred to
the Muses as distinct from Apollo.

	|19-21.~  Compare ^Purg.~ i. 7-12.  The underlying motive
seems to be an appeal to the deities to proclaim their glory
through their willing instrument as zealously as they vindicated
their honour against presumptuous rivals.  Marsyas was flayed by
Apollo for his presumption in challenging him to a contest in
playing the pipe.  Hence the allusion to the "sheath of his
limbs."

	|32-33.~  Daphne, the daughter of Peneus, loved by
Apollo, was changed into a laurel.

	|36.  Cirrha.~  Apollo's peak of Parnassus.

	|37-39.~  The circles of the Equator, the Zodiac and the
Equinoctial colure, make each a cross with the circle of the
horizon.  At the equinox, at sunrise, they all meet the horizon
and make their crosses with it at the same spot.

	|43.~  ^Had made~, viz. when he rose.  It was now noonday
(44, 45).

	|49-54.~  The point of analogy appears to consist simply
in the derivative character of Dante's act.

	|57.~  The Earthly Paradise or Garden of Eden (^Purg.~
xxviii. 91-93).

	|61-63.~  Owing to their rapid approach to the sun.
Compare also ^Purg.~ xxvii. 89, 90.

	|64.  Wheel~ or ^wheels~, here and throughout the
^Paradiso~ used for the revolving heavens.

	|68.~  Ovid tells the tale of the fisherman Glaucus
tasting the grass that had revivified the fish he had caught, and
thereon being seized with yearning for the deep, into which he
plunged and became a sea god.

	|73.~  Compare 2 ^Corinthians~ xii. 2.  The soul is
enbreathed by God when the animal body is perfected (^Purg.~ xxv.
67-75), and is therefore that part of a man which is to be
regarded as a new creation by God, not generated by nature.
Compare iii. 87, ^note~, and Wallace, 56, ^note~ 3.

	|76.~  It is by inspiring the universe with love and
longing (not by any physical means, for he is immaterial) that
God, according to Aristotle, causes the never-ending cosmic
movements.  Wallace, 39.

	|79-81.~  Because they were passing through the "sphere
of fire" which girt the "sphere of air" as with a second
atmosphere.

	|82.~  The conception that the seven planetary heavens,
like the seven strings of a lyre, uttered divine harmonies as
they moved, is expressly rejected by Aristotle.  This is one of
the few instances in which Dante departs from his authority.

	|90.~  It, ^i.e.~ the ^false imagining~, the fixed idea
which prevented his comprehending what was before his eyes.

	|92.~  ^Cf.~ xxiii. 41-42.

	|99.~  Air, which Aristotle regarded as relatively, and
^fire~ which he regarded as absolutely light.

	|106.  ^Exalted creatures~ = angels [and men?].

	|107-114.~  God is the goal as well as the source of all.
The orderly trend of all things to their true places is therefore
their guide to God.  But all things do not reach God in the same
sense and in the same measure.  

	|119.~  ^Cf.~ xxix. 24.

	|122-123.~  The Empyrean, which is not spatial at all,
does not move and "hath not poles."  It girds with light and love
the ^Primum Mobile~, the outmost and swiftest of the material
heavens.  Compare ^Paradiso~, xxii. 67, xxvii. 106-120, xxx. 38-
42, 52, etc.  Also ^Conv.~ ii. 4: 13-43.

	|127-135.~  `As the medium in which an artist works
sometimes appears to resist the impulse and direction which he
would give it, so beings endowed with free-will ("the creature
that hath power...to swerve aside") may resist the impulse
towards himself impressed upon them by God, if they allow
themselves to be seduced by false delights.'
