	|4-6.  nel suo giro~, &c.: `had not completely described its
circle.'  |un' altra~: from l. 96 we learn that the two circles
were composed of twenty-four spirits in all.  |E moto~, &c.: `and
danced and sang in corresponding measure'; lit. `took up its
movement by the other's movement, and its singing by the 
other's singing.' 

	|8-9.  Sirene~: `sweet singers.'  |tube~: `instruments,'
i.e. the spirits who sang.  |quel ch' ei refuse~: `the light 
which it gives by reflexion'; `as much as the original ray 
surpasses in brightness the reflected ray.' 

	|10-12.  Come~, &c.: `as through a filmy cloud two arcs are
described, corresponding in lines and colours.'  |per tenera
nube~ means that the rainbow is formed by the sunlight passing 
through a fine cloud dissolving in rain.  Note the three similes,
one within the other: (1) the two circles of saints are like the
double rainbow; (2) the formation of the second rainbow is like 
that of the echo; (3) the death of the nymph Echo through pining
for love is like vapours being dried up by the sun.  |sua
ancella~: Iris, the rainbow, was the handmaid of Juno. 

	|14-15.  quella vaga~: `that wandering sprite.' |Ch' amor~,
&c.: Echo wasted away through love of Narcissus until only her
bones and her voice remained.  The story is given in Ov. ^Met.~
iii. 356 foll., where her death is thus described -- `Attenuant
vigiles corpus miserabile curae, Adducitque cutem macies, et in
a,era sucus Corporis omnis abit; vox tantum atque ossa supersunt
(ll. 396-8).' 

	|16-18.  E fanno~, &c.: `and (the rainbows) cause mankind to
augur...that the world will not henceforth be destroyed by a
flood'; cp. Gen. ix. 12-5. 

	|21.  estrema~: the outermost.  |ultima~: the innermost. 

	|22-24.  tripudio~: `dance,' Lat. ^tripudium.~  |Luce~, &c.:
this is a pendent clause, though perhaps the words may be in
apposition to |tripudio~ and |festa~ (`consisting of lights,'
&c.).  Scartazzini removes the comma after |fiammeggiarsi~, and 
brings the clause under its construction. 

	|25-26.  Insieme~, &c.: `paused correspondingly in time and
in accord'; at the same moment and unanimously.  |al piacer~,
&c.: `in accordance with the volition which moves them.' 

	|28-30.  una~: St. Bonaventura; on him see note on l. 127. 
|che l' ago~, &c.: `which caused me in turning towards its 
position to resemble the magnetic needle turning towards the 
pole-star.'  For the substantival use of |dove~ cp. ^ogni dove~
in Par. iii. 88.  The point of comparison is the
instantaneousness of the responsive movement.  The magnetic
needle is shown to have been used before this time to indicate
the pole-star by the mention of it in Brunetto Latini's ^Tesoro~,
Bk. ii. Ch. 49; and other evidence to the same effect has been
collected by Humboldt in his ^Cosmos~, vol. ii. pp. 629, 630,
Ott$e's trans. 

	|32.  altro duca~: St. Domenic (1170-1221).  He was born at
Calahorra in Old Castile in Spain, and was noted from an early 
period of his life for his self-denial and charity.  In his 
maturer years he was distinguished as a champion of orthodoxy, 
and he took an active part in combating the doctrines of the 
Albigenses.  The preaching Order of the Dominicans, which he 
founded, received the formal sanction of Pope Honorius III in 
1217. 

	|33.  Per cui~, &c.: `by reason of whom such praise is 
accorded to my leader,' St. Francis.  Cp. Par. xi. 118-20, where
it is seen that the praise of St. Francis was intended to lead up
to that of his compeer, St. Domenic. 

	|35.  ad una~: `together,' i.e. in the same service; cp.
Purg. ix. 63. 

	|38-39.  riarmar~: `to arm afresh' against the assaults of
the Devil; this was effected by Christ's death.  Man at his
creation wore the armour of innocence; he lost this at the Fall,
but was regenerated by Christ's death, and so was provided with 
fresh armour.  |Si movea~: `was moving'; this refers to the
period preceding the establishment of the two Orders.
|suspiccioso~: `without confidence.' 

	|41.  alla milizia~, &c.: `for his soldiers who were
wavering.'  For other instances of |in forse~ in the sense of `in
doubt' cp. Inf. viii. 110; Purg. xxix. 18. 

	|43-45.  com' @e detto~: cp. Par. xi. 31-6.  |sua sposa~: 
the Church.  |si raccorse~: from ^raccorgersi~, `bethought them 
of their errors.' 

	|46.  quella parte~: Spain, the land from which the West 
wind comes. 

	|49-52.  Non molto~, &c.: `not far removed from the beating
of the waves, behind which, to repose from (lit. because of) his
long impetuous course (|la lunga foga~), the sun at times hides
him from men, lies Calahorra the fortunate.'  By |la lunga foga~
is meant the sun's course in summer) when it is longest; |tal
volta~ (`at times') signifies `in the summer season'; and by 
|onde~ the Bay of Biscay is intended, because in the summer the 
sun sets to the W. of N., which is the direction of that bay from
the point of view of Italy.  This interpretation suits the 
position of Calahorra (|Calaroga~), which lies near the upper 
waters of the Ebro, and is `not far removed from' the Bay of 
Biscay, whereas it is at a great distance from the Atlantic.  For
the use of |tal volta cp.~  Par. xi. 51.  |fortunata~: as being 
St. Domenic's birthplace. 

	|53-54.  scudo~, &c.: `shield,' `coat of arms.'  In one of
the quarterings of the arms of Spain the Lion is above the
Castle, in another beneath it.  These emblems represent the 
kingdoms of Leon and Castile. 

	|55-57.  l' amoroso drudo~: `the passionate lover.' 
|crudo~: `harsh,' `severe,' as being a strong opponent of 
heretics.  It is not certain whether he encouraged the 
persecution of the Albigenses, but he undoubtedly took part 
against them. 

	|58-60.  come~: `as soon as'; cp. Par. xv. 74. `His spirit,
as soon as it was created, -- was so replete with living power,
that while he was in his mother's womb it caused her to be
prophetic.'  Before the birth of St. Domenic his mother dreamed 
that she had brought forth a dog, spotted black and white, which
bore a lighted torch in its mouth.  The figure of the spotted dog
was emblematic of the black and white dress of the Dominican 
Order, and in that connexion was frequently at a later time 
introduced in art with a play on ^Domini canes~, the Dominicans 
being regarded as the Lord's watchdogs. 

	|61.  le sponsalizie~: `the espousals' are his baptism, when
he plighted himself to the Christian faith. 

	|64-66.  La donna~, &c.: his godmother dreamed that he bore
a star on his forehead, which illumined the world.  |erede~: his
followers; cp. Par. xi. 112. 

	|67-69.  perch@e~, &c.: `that he might be in name what he 
was in reality.'  |costrutto~: `the form of his name'; similarly 
in Purg. xxviii. 147 ^costrutto~ means `a form of words' or 
`sentence': and in Par. xxiii. 24 ^senza costrutto~ is `without 
putting it into words.'  |Quinci~, &c.: the meaning is: -- `An 
inspiration from Heaven (|Quinci~) was communicated to his 
parents to name him by the possessive adjective (viz.
^Dominicus~) derived from the name of the Lord (^Dominus~) who 
possessed him entirely.' 

	|71.  CRISTO~: observe that here and elsewhere no other word
is allowed to rhyme with the name of Christ. 

	|75.  primo consiglio~: `prime counsel,' i.e. counsel of
perfection; Matt. xix. 21, `If thou wilt be perfect, go and sell
that thou hast, and give to the poor,' &c.  For St. Domenic's
observance of this rule see note on l. 32. 

	|76-78.  Spesse fiate~, &c.: these are instances of his 
early renunciation of everything temporal for Christ.  He was 
found by his nurse awake and kneeling on the earth in silent 
prayer.  |Io son~, &c.: `I have come into the world for this,' 
viz. to watch and pray and renounce enjoyments. 

	|79-81.  veramente~: `rightly named.'  |Giovanna~: `favoured
by God,' according to its meaning in Hebrew.  In the next line
Dante confesses his ignorance of that language.  He may have got
the interpretation from Isidore, ^Orig.~ vii. 9; or from the
^Magnae Derivationes~ of Uguccione da Pisa; see Toynbee, ^Dict.~,
p. 277. 

	|83.  Ostiense~: Henry of Susa, Cardinal, and Bishop of 
Ostia, d. 1271.  He wrote a commentary on the Decretals.  For the
study of these as a worldly pursuit cp. Par. ix. 134, 135. 
|Taddeo~: Taddeo Alderotti of Bologna, a celebrated physician, 
d. 1303.  In this line and l. 92 the pursuit of preferment or 
gain in the three learned professions is referred to, as above in
Par. xi. 4, 5. 

	|86-87.  la vigna~: the Church.  |imbianca~: `is bleached,'
i.e. fades and withers. 

	|88-90.  alla sedia~, &c.: governed by ^Addomand@o~ (l. 94);
`he requested of the Holy See...not opportunities of enriching
himself (^Non dispensare~, &c., ll. 91-3), but,' &c.  |gi@a fu~,
&c.: `aforetimes was kinder,' i.e. is now less kind than of old. 
|non per lei~, &c.: this is a comment on the preceding clause;
`not by its own doing, but by his who occupies it, who goes
astray': the Pope is meant, and Boniface VIII in particular. 

	|91-93.  dispensare~, &c.: `the power of giving away (lit. 
distributing) one-third or one-half (of moneys bequeathed for 
benevolent purposes),' and keeping back the rest.  |la fortuna~, 
&c.: `the opening offered by the first vacant benefice'; |prima~
probably agrees with ^ecclesia~ understood.  The reference is to
the ^expectationes~, or nominations to posts not yet vacant,
which the Popes of that time used to make.  |decimas~, &c.: `the
tithes which rightly belong to God's poor'; the words are in 
Latin, because that is the language of the Church or of Canon 
law. 

	|94-96.  contro~, &c.: St. Domenic visited Rome in 1205, 
and in 1207 commenced preaching against the Albigenses.  |lo 
seme~, &c.: `the seed from which are sprung the twenty-four 
plants which encircle thee,' i.e. the Faith, by which the 
theologians who form two circles round thee were nurtured. 

	|97-99.  volere~: i.e. zeal.  |l' offizio apostolico~: 
`his apostolic office,' i.e. the authority conferred upon him 
by Innocent III.  |ch' alta~, &c.: `bursting from an elevated 
source.'  As a `torrent' is being spoken of, and its impetus is 
the point of the comparison, |alta~ seems to mean `elevated' 
rather than `deep-seated,' as some explain it.  Moreover 
Aristotle who on points like this is Dante's usual authority, 
remarks on the high position of the sources of rivers; 
^Meteorol.~ i. 13. 11, %alpha%iota\ %kappa%rho%eta%nu%alpha%iota\
%alpha%iota\ %pi%lambda%epsilon%iota%sigma%tau%alpha%iota\
%omicron%rho%epsilon%sigma%iota\ %kappa%alpha%iota\
%tau%omicron%pi%omicron%iota%sigma\
%upsilon%psi%eta%lambda%omicron%iota%sigma\
%gamma%epsilon%iota%tau%nu%iota%omega%sigma%iota%nu\. 

	|101.  quivi~: in the neighbourhood of Toulouse, which was
the chief centre of the Albigenses. 

	|103.  diversi rivi~: the followers of St. Domenic.  They 
were the streams, which proceeded from the torrent, and 
fertilized the garden of the Church (|l' orto cattolico~). 

	|106-108.  biga~: Lat. for `two-horsed car'; here used by 
Dante for `two-wheeled car.'  The Church has already been 
represented by this emblem in the triumphal procession in Purg. 
xxix. 107.  In the present passage the two wheels are the 
founders of the two great Orders.  |civil briga~: `civil war,' 
i.e. the contest with heresy, which was a struggle within the 
Church itself. 

	|110-111.  dell' altra~, &c.: of St. Francis, who was 
lauded by St. Thomas Aquinas in the preceding Canto. 

	|112-114.~  St. Bonaventura now proceeds to denounce the 
degeneracy of his own Order, the Franciscans, as in Par. xi. 124
foll.  Aquinas had denounced that of the Dominicans.  |orbita~: 
Lat. for `wheeltrack.'  |la parte somma~, &c.: `the topmost part 
of the circumference of the wheel'; by this expression St. 
Francis himself is meant.  His followers had forsaken his track.
|la muffa~, &c.: the metaphor is taken from a cask of wine; 
`where once the crust was, there is now the mould.' 

	|117.  quel dinanzi~, &c.: `his family (the Franciscan
Order) sets (|gitta~) the point of the foot (|quel dinanzi~, the 
forepart) upon the heel (|quel diretro~, the hinder part); i.e.
they follow their leader's footsteps in the exactly opposite 
direction. 

	|118-120.  E tosto~, &c.: `and soon there will be evidence 
of the harvest (i.e. result) of this bad husbandry, when the 
tares complain that they are excluded from the granary,' i.e. 
when the unprofitable brethren complain that they are excluded 
from the Church.  The reference is to the sect of the 
Spiritualists, or rigid maintainers of the Franciscan rule, who 
separated from that Order and from the Church; see note on ll. 
124-6.  This schism St. Bonaventura says, was the result of 
previous corruption in the Order.  Another and simpler 
interpretation of the passage would make it refer to the
Judgement when the tares shall be burnt and the wheat gathered
into the barn (Matt. xiii. 30); but this is hardly admissible,
for in that case |tosto~ would imply that Dante believed the end
of the world to be close at hand. 

	|121-123.  Ben dico~, &c.: the Saint guards against too 
sweeping a condemnation by saying that there are exceptions. 
`Doubtless I would affirm that, should one examine our volume 
leaf by leaf, he would still find pages where he could read the 
words "I am as I am wont."' Some members of the Order maintain 
their profession still unchanged. 

	|124-126.  Ma non~, &c.: `but such an instance will not be 
derived from Casale, nor from Acquasparta, the representatives of
which places so interpret the rule of the Order (|la scrittura~),
that while the latter shirks it, the former makes it more 
stringent.'  In 1289 Matteo d' Acquasparta, general of the 
Franciscans, relaxed the rule; but, in reaction from this, 
Ubaldino di Casale insisted on a stricter interpretation, and 
headed the sect of the Spiritualists. 

	|127-129.  vita~: `spirit.'  |Bonaventura~: he was called 
the ^Doctor Seraphicus~, and was born in 1221 at Bagnoregio (now
Bagnorea, near the lake of Bolsena), and became general of the 
Franciscan Order.  His views were Platonist and mystical, and in
this respect he formed a strong contrast to Aquinas, who was 
Aristotelian and logical.  Dr. Liddon has suggested, that the 
fact that the two died within four months of one another may have
had much to do with the position assigned to Bonaventura in the 
Paradiso (^Essays and Addresses~, p. 199).  |la sinistra cura~: 
the desire of temporal advantages; cp. Aquinas, ^Summa~, i. 
2d+ae~. Q. 102. Art. 4, `Sapientia pertinet ad dextram, sicut et
caetera spiritualia bona; temporale autem nutrimentum ad 
sinistram, secundum illud Prov. iii. 16, in sinistra illius 
divitiae et gloria.' 

	|130-132.~  St. Bonaventura now proceeds to name the spirits
who form the outer circle, as St. Thomas had named those of the
inner circle.  |Illuminato ed Augustin~: two early followers of
St. Francis.  |scalzi~: `barefooted friars'; cp: Par. xi: 80. 
|capestro~: ^ibid.~ l. 87. 

	|133-135.  Ugo~, &c.: Hugo of St. Victor, a mystic and 
theologian;, see note on Par. x. 131.  |Pietro Mangiadore~: 
Petrus Comestor (Cent. xii.), so called as being a devourer of 
books.  |Pietro Ispano~: Petrus Hispanus; he became Pope John XXI
in 1276.  The |libelli~ here mentioned are his ^Summulae
Logicales.~  |gi@u~: in the world below. 

	|136-138.  Natan~: Nathan, who rebuked David; 2 Sam. xii. 
7 foll.  He is supposed to be introduced here as a companion to 
St. Chrysostom, because both rebuked kings.  Chrysostom opposed 
the emperor Arcadius.  |il metropolitano~: he was Patriarch of 
Constantinople.  By his homilies he deserved a place among the 
theologians.  |Anselmo~: St. Anselm (Cent. xii.); Archbishop of 
Canterbury; author of the ^Cur Deus homo.~  |Donato~: Donatus, 
the grammarian of Cent. iv., and author of the Latin grammar. 
St. Jerome was one of his pupils.  |prim' arte~: Grammar, which 
was the first in order of the seven sciences of the Trivium and 
Quadrivium; see ^Conv.~ ii. 14. ll. 55-7. 

	|139-141.  Rabano~: Rabanus Maurus (Cent, viii. and ix.), 
theologian, and Bishop of Mainz.  |Gioacchino~: the Abbot Joachim
of Calabria (Cent. xii.), mystic and theologian.  After his death
he was credited with numerous visions and prophecies. 

	|142-145.  Ad inveggiar~, &c.: `to celebrate this mighty 
champion of the Faith.'  St. Domenic, of whom Bonaventura has 
been speaking, must here be meant, and this determines the 
meaning of |inveggiar.~  From signifying `to envy' it seems to be
used in the favourable sense of `to hold up to wondering 
admiration.'  |cortesia~: this was shown by St. Thomas, a 
Dominican, singing the praises of St. Francis.  |il discreto 
latino~: `his discreet address'; for |latino~ see note on Par. x.
120.  |mosse~, &c.: the outer circle danced and sang at the 
conclusion of St. Thomas's address, as described in ll. 5, 6. 

