	|1-18.  Ecco la fiera...per Aragne imposte~: The aura of
suspense generated by the figure closing Canto XVI (^Inf.~ XVI,
131-36) continues here at the beginning of Canto XVII as Virgil
points to the beast that emerges from the depths, "swimming"
through the air.  Before we see the monster in his literal shape,
his allegorical significance as fraud is emphasized (vs. 7).  His
name, Geryon, is withheld until vs. 97.

	Whereas Dante's monster has three natures -- those of man,
beast, and serpent -- the monster Geryon of classical literature,
after whom he is named, had three bodies and three heads.  Thus
Virgil (^Aen.~ VIII, 202) refers to ^tergeminus Geryon.~  For
Geryon's treacherous nature Dante apparently drew on the medieval
tradition according to which he lured strangers into his power
and then slew them.  For instance, Boccaccio says of Dante's
monster (^Geneal. deor. gent.~ I, 21): "Et inde Gerion dicta,
quia regnans apud Baleares insulas Gerion miti vultu, blandisque
verbis et omni comitate consueverit hospites suscipere, et demum
sub hac benignitate sopitos occidere."  ("It is named after
Geryon, who reigned near the Balearic Islands.  With a mild face,
with sweet words, using every politeness, he used to attract
strangers to him; and then, having lulled them with his
benignity, he would slay them.")

	Certain other features of Dante's description of the
monster probably were borrowed from the Bible.  Geryon's
reptilian form, appropriate to his role as the "foul image of
fraud" (vs. 7), may have been suggested by Gen. 3: 1 and II Cor.
11:3.  His human face and pointed tail may derive from Apoc. 9:7,
10:

     Et similitudines locustarum similes equis paratis in
     proelium...et facies earum tamquam facies hominum ...et
     habebant caudas similes scorpionum, et aculei erant in
     caudis earum: et potestas earum nocere hominibus....

     And in appearance the locusts were like horses made ready
     for battle...and their faces were like the faces of
     men...And they had tails like those of scorpions and there
     were stings in their tails; and they had power to harm
     mankind....

Dante also may have drawn on Solinus, Latin grammarian and writer
probably of the third century, who gives the following
description of the ^mantichora~, a fabulous Indian beast, in his
^Collectanea rerum memorabilium~ (LII, 37-38):

     Facie hominis...corpore leonino, cauda velut scorpionis
     aculeo spiculata....pedibus sic viget, saltu sic potest, ut
     morari eam nec extentissima spatia possint nec obstacula
     latissima.

     He walks about with the face of a man, the body of a lion,
     and his tail is spiked as is the stinging tail of a
     scorpion....He has so much power with his feet and he is
     able to jump so far that neither the greatest distance nor
     the broadest barriers can withstand him.

On Geryon see R. T. Holbrook (1902), pp. 62-66; F. Cipolla
(1894-95); A. R. Chisholm (1929); A. Sepulcri (1916); E. Proto
(1900); B. Soldati (1903).

	|2.  che passa i monti e rompe i muri e l'armi~: No
defense, either natural or man-made, can avail against the beast.

	|5.  accennolle~ = ^le accenn@o.~

	|proda~: Literally, "shore"; see ^Inf.~ VIII, 55.  Here in
Canto XVII the word refers to the very end of the bank, or dike
("passeggiati marmi," vs.  6), along which the two wayfarers have been
walking.

	|6.  d'i~ = ^dei.~

	|7.  froda~ = ^frode~; for other occurrences of this form,
see E.G. Parodi (1957), p. 244.

	|8.  arriv@o~: "Brought ashore."   The verb is transitive
here; its objects are "testa" and "busto."

	|9.  non trasse la coda~: As it were, concealing this
"weapon."

	|10.  era faccia d'uom giusto~: See Apoc. 9:7, quoted
above in n. to vs. 1.  See also ^Conv.~ IV, xii, 3:

     E quelle cose che prima non mostrano li loro difetti
     sono pi@u pericolose, per@o che di loro molte fiate prendere
     guardia non si pu@o; s@i come vedemo nel traditore, che
     ne la faccia dinanzi si mostra amico, s@i che fa di s@e
     fede avere, e sotto pretesto d'amistade chiude lo
     difetto de la inimistade.

     And those things which at first conceal their defects are
     the most dangerous; because, in many cases, we cannot be on
     our guard against them, as we see in the instance of a
     traitor who in appearance shows himself a friend, so that he
     begets in us a confidence in him, and beneath the pretext of
     friendship he hides the fault of enmity.

	|11.  tanto benigna avea di fuor la pelle~: The subject
of "avea" is "faccia" in the preceding verse./  Commenting on
Apoc. 9:5, Thomas Aquinas mentions the deceptively benign face of
the scorpion in ^Exp.  I super Apoc.~ IX (p. 399):

     "Et cruciatus eorum," idest illatus ab eis, "ut cruciatus
     scorpii," cuius cruciatus valde gravis est, et vix potest
     sanari "cum percutit hominem," facie blandiens, et cauda
     pungens.

     "Their sting" -- that is, the wound that they cause -- "is like
     the sting of a scorpion," whose sting is very serious
     indeed.  Nor can it be cured "when he strikes a man," with a
     smiling face and a sting in his tail.

	|12.  fusto~: "Trunk."

	|13.  due branche~: Boccaccio comments: "due piedi
artigliati, come veggiamo che a' dragoni si dipingono" ("two
clawed feet, such as we see on dragons in paintings").

	|insin~ = ^fino a.~

	|14.  le coste~: The sides of the monster's body.

	|15.  dipinti~: Reminiscent of the "pelle dipinta" of the
"lonza" (^Inf.~ XVI, 108).

	|rotelle~: Dragons were sometimes depicted in medieval
manuscripts with little circles or rings covering their bodies; see R.
T. Holbrook (1902), pp. 63, 65.

	|16.  sovraposte~: P. Toynbee (1902, pp. 115-18) argues
from ample documentation that this word (or the variant form
^sopraposte~) means "embroidered patterns."

	|17.  fer~ = ^fecero.~

	|drappi~: The direct object of "fer."

	|drappi Tartari...Turchi~: The so-called Tartar cloths
were in high repute during the Middle Ages.  P. Toynbee (1902, p.
119) quotes Nerio Moscoli, a poet of the thirteenth century, who
speaks of cloth so rich that "niun tartaresco Paregiar lo
porria."  ("No Tartar cloth could match it.")  And Boccaccio
(^Decam.~ VI, 10; vol. II, p. 28, ll. 9-10) describes a garment
"con pi@u macchie e di pi@u colori che mai drappi fossero
tartereschi o indiani" ("with even more designs and more colors
than the Tartar or Indian fabrics").  Turkish fabrics were also
famous and highly valued in the Middle Ages.

	|Tartari...Turchi~: Both peoples were treacherous, from
the Christian point of view, as their mention here, in connection
with the "foul image of fraud," suggests.  See a similar
reference to mosques glimpsed within the city of Dis (^Inf.~
VIII, 70 and the note).

	Boccaccio's ^Comento~ ends abruptly midway through his
observations on ^Inf.~ XVII, 16-17.  He died, as P. Toynbee
(1907, p. 103) says, almost as though with pen in hand, for his
last sentence remained unfinished.

	|18.  fuor~ = ^furono.~

	|Aragne~: In Greek mythology Arachne, who excelled in weaving,
challenged Minerva to a competition. Unable to find fault with
Arachne's work, Minerva tore it to pieces.  In despair Arachne hanged
herself, but the goddess loosened the rope and changed her into a
spider.  Ovid tells the story in the ^Metamorphoses~ (VI, 5-145).
Arachne has an allusive function here similar to that of the Tartars
and Turks in the preceding verse: the spider's web also suggests
cunning and treachery.

	|imposte~: Probably "placed" upon the loom, although the term
can mean "designed"; see M. Barbi (1934b), p.  241.

	|19.  burchi~: Plural of ^burchio~, a kind of rowboat
sometimes equipped with a cover.  This cover may be intended as
part of the image here, since it would suggest some kind of
cloth, possibly colored and printed with a design.

	|21.  Tedeschi lurchi~: According to a tradition recorded
as early as Tacitus, gluttony was characteristic of the Germans;
see A. Sepulcri (1916), pp. 179-82.

	|22.  lo bivero~: Cf. the Latin ^biber~; the commoner
Italian word is ^castoro.~  Dante probably shared a popular
belief, delineated later by his son, Pietro di Dante: "Dicitur de
bivero animali, quod cum cauda piscatur mittendo ipsam in aquam
et ipsam agitando, ex cuius pinguedine resultant guttae ad modum
olei, et dum pisces ad eas veniunt, tunc se revolvendo eos
capit."  ("It is said that the beaver fishes by putting its tail
in the water and agitating it; the fat in the tail squirts forth
drops similar to oil and when the fish are attracted to these
drops, the beaver turns around and grabs them.")  In point of
fact, the beaver is not a fish-eater and was notoriously confused
with the otter and the badger, which do feed on fish.  Moreover,
while beavers abounded in Germany in Dante's time, they were not
common as far south as Italy -- although Benvenuto cites the
contrary view: "Inveniuntur hic non longe a Ferraria in
territorio Marchionum Estensium."  ("They are to be found here
too, not far from Ferrara, in the territory of the marquis of
Este.")  On ancient and medieval knowledge of the beaver, see A.
Sepulcri (1916), pp. 171-72.

	Dante intended the beaver -- like the Tartars and Turks and
Arachne -- to represent craft and deception. The image of the
beaver awaiting its prey fits the description of Geryon, lying in
wait on the bank, his tail (armed at the point for a purpose too)
thrust out into the void, which already (^Inf.~ XVI, 133-36) has
been compared to water.

	|22.  s'assetta~: "Settles itself"; see vs. 91.

	|24.  su l'orlo ch'@e di pietra e 'l sabbion serra~: The
rim of the precipice, an edge of rock, is sheltered from the
fire, as are the banks of the conduit; see vss. 32-33, 43-45.

	|30.  corca~ = ^corica.~

	|31.  scendemmo a la destra mammella~: Virgil and Dante
have been walking along the right bank of the conduit; they must
now descend the right side of that bank, since the boiling stream
lies to their left.  On a possible symbolic meaning of this
second turn to the right in Hell (the first turn to the right is
discussed in n. to ^Inf.~ IX, 132), see J. Freccero (1961a), p.
180:

     As heresy is the perversion of the intellect's higher
     function, the speculative activity of theology and moral
     philosophy, so usury is a sin of its lower activity: human
     industry, or art.  Usury for this reason is also a sin
     against nature and God Himself....This is the only sin in
     Dante's ^Inferno~ which the poet specifically tells us is
     against human industry, for it is the only sin which
     methodically and systematically reproduces the materials it
     began with in a parody of productivity which is in fact
     sterile. It is to counter this perversion of the practical
     reason that the poet retrogresses for the second time "to
     the right."

	|32.  diece passi~: "Ten" is merely an approximate number
and holds no evident symbolic meaning here.

	|femmo~ = ^facemmo.~

	|lo stremo~: The outer rim of the circle.

	|33.  cessar~: "To avoid."

	|34.  semo~ = ^siamo.~

	|35-36.  in su la rena gente seder~: These shades who sit
upon the burning sand are the usurers.  They are identifiable
both from Virgil's exposition in Canto XI (vss. 46-51) of the
three categories of sinners condemned to the seventh circle, and
from Dante's description (^Inf.~ XIV, 19-24) of the different
postures assumed by these three groups when they are first
observed on the fiery plain. Until now the usurers have not, so
postured, come into the picture again. The wayfarer must hear
them and note their condition more closely in order to have "full
experience" (vss. 37-38) of this ^girone.~

	|39.  mena~: The manner of their punishment.

	|41.  mente che~ = ^finch@e.      con questa~: The
antecedent is "bestia" (vs. 30).

	|43.  ancor~: Dante has already taken "ten" steps along
the rim.

	|44.  tutto solo~: This is the first time in the
^Commedia~, and the only time in the ^Inferno~, that Dante
proceeds alone, without Virgil's guidance.

	|46.  fora~ = ^fuori.~

	|47.  soccorrien~ = ^soccorrevano.~

	|47-48.  soccorrien con le mani...suolo~: The usurers
attempt to defend themselves by brushing off the burning flakes
of fire (see "arrostarsi," ^Inf.~ XV, 39) and by raising
themselves on their hands to relieve their burning rumps.

	|52.  a certi~: None prove to be Jews or moneylenders of
low station; all are Christians, from distinguished Florentine
and Paduan families.

	|54.  non ne conobbi alcun~: Except by the escutcheons on
their moneybags (vs. 56) -- their only real identity -- the usurers
are unrecognizable.  Similarly, the avaricious and the prodigal
had been rendered unrecognizable by their sins; see ^Inf.~ VII,
53-54: "la sconoscente vita che i f$e sozzi / ad ogne conoscenza
or li fa bruni."

	|55.  tasca~: A common term for a moneychanger's purse
(it is also called a "borsa" in vs. 59 and a "sacchetto" in vs.
65).  G. Salvemini (1902, p. 115) notes the use of the same word
in a document of 1299 (in Latin) which refers to the custom of
moneylenders who sit "ad tabulam sive banchum cum tascha et
libro" ("at a table or bench with a wallet and a book").  Here in
Canto XVII the usurers sit "crouched up" (as they were described
in ^Inf.~ XIV, 23), feasting their eyes (vs. 57) on the coats-
of-arms on their moneybags.

	|56.  certo colore~: The background color.

	|certo segno~: The design of the escutcheon.

	|57.  e quindi par che 'l loro occhio si pasca~: See a
similar use of "eyes" ("oculi") in Eccles. 4:7-8: "Considerans
reperi et aliam vanitatem sub sole: unus est et secundum non
habet, non filium, non fratrem, et tamen laborare non cessat, nec
satiantur oculi eius divitiis."  ("Again I found this vanity under
the sun: a solitary man with no companion; with neither son nor
brother.  Yet there is no end to all his toil, and [his eyes are
not satisfied by riches].")

	|58.  E com' io riguardando tra lor vegno~: "As I
continue to look among them."

	|59-60.  in una borsa gialla...contegno~: The arms of the
Gianfigliazzi of Florence were "on a field or a lion azure."
According to Villani, the family, who were Guelphs, lived in the
section of Florence (which at one time was divided into "sixths")
known as the Sesto di Borgo (V, 39).  They were exiled from
Florence with other prominent Guelph families in 1248 and again
in 1260 after the battle of Montaperti (VI, 33, 80); and when the
Guelph party later split into the Bianchi and Neri factions, they
sided with the Neri (VIII, 39).  They were still prominent in the
fourteenth century (XII, 3).  F. P. Luiso (1908) holds that
Dante refers here to Messer Catello di Rosso Gianfigliazzi, who
practiced usury in France and was made a ^cavaliere~ on returning
to Florence.  He died some time after 1283. M. Barbi (1934b, pp.
270-72) gives a fuller biography.

	|61.  procedendo di mio sguardo il curro~: A grammatical
construction similar to the ablative absolute.~     ^|l curro~ = ^il
corso~; some commentators understand it as ^carro.~

	|62.  vidine~ = ^ne vidi.~

	|62-63.  un'altra come sangue rossa...burro~: The arms of
the Florentine Ubbriachi (or Obriachi) were "on a field gules a
goose argent."   Villani states that the Ubbriachi were
Ghibellines (V, 39; VI, 33) who lived in the Sesto d'Oltrarno and
were among those expelled from Florence in 1258 (VI, 65).

	|64.  una scrofa azzurra e grossa~: The arms of the
Scrovegni family of Padua were "on a field argent a sow azure."
The usurer in question is thought to be Rinaldo (or Reginaldo)
Scrovegni, who amassed one of the largest personal fortunes in
Padua.  The first documentary mention of him is in 1263; he died
some time between March 1288 and October 1289.  His son Enrico
commissioned the famous chapel of the Scrovegni frescoed by
Giotto.  On the Scrovegni see G. Biscaro (1928).

	|66-67.  Che fai tu in questa fossa? Or te ne va~: This
is the first of a number of angry challenges addressed to the
wayfarer as he proceeds through lower Hell.

	|66.  fossa~: The cavity of Hell itself (see ^Inf.~ XIV,
136).  Thus, as the next verse makes clear, the challenge is to
the living man.

	|67.  te ne va~ = ^vattene.~

	|anco~ = ^ancora.~

	|67-73.  e perch$e se' vivo...becchi~: Also for the first
time a soul maliciously names other sinners here present in the
hope that the wayfarer will report their shameful deeds to the
world of the living.  Unlike the souls Dante has already met
among the incontinent of upper Hell and the violent of the first
circle of lower Hell, some of the shades he encounters among the
fraudulent punished in the lowest circles will wish not to be
remembered in the "sweet world" above.  This incident, taking
place as it does on the verge of those circles (the eighth and
ninth), seems to foreshadow that new attitude.

	|68.  'l mio vicin~: "My fellow townsman"; see ^Purg.~
XI, 140.

	|Vitaliano~: The early commentators state that this
sinner still among the living was Vitaliano del Dente, who
appears to have been an important person in Padua, where he was
^podest@a~ in 1307.  He is mentioned as a moneylender in several
documents of the late thirteenth century.  E. Morpurgo (1865, pp.
213-15, 231) thinks the reference is to a certain Vitaliano di
Jacopo Vitaliani, who is mentioned as a usurer in an old Paduan
chronicle (supposedly written in 1335), in which Dante's
condemnation of him to Hell apparently is alluded to: "Et unus
dominus Vitalianus potens et ditissimus vitam mirabilem in
peccatis duxit, quoniam maximus usurarius fuit, quem doctor
vulgaris damnat ad inferos permanere."  ("There was a man named
Vitaliano who, with his power and wealth, led an extraordinary
life of sin. He was the greatest of usurers and for this reason
the doctor of the vernacular condemns him to eternal hell.")

	|70.  Con questi Fiorentin~: The thrust at Florence as a
nest of usurers, "noble" usurers, is strong; it reaches a climax
in vss. 71-72.

	|72.  'l cavalier sovrano~: This is the Florentine usurer
Giovanni (or Gianni) Buiamonte of the Becchi family. M. Barbi
(1925b) states that he was born in 1260 and died in 1310; he was
of a Ghibelline family of the Sesto di Porta San Pancrazio, and
his father had himself been a ^cavaliere~; in 1293, Giovanni was
^gonfaloniere di giustizia~, and thereafter until his death his
name was frequently recorded in Florentine documents. It is
uncertain precisely when Giovanni Buiamonte was made a
^cavaliere~, but Barbi (1925b, pp. 67-68) cites documentary
evidence to prove that the honor was conferred at some time
before 1298.  The souls in Hell, then, correctly address Giovanni
as "the sovereign knight," since Dante's fictional journey takes
place in 1300.

	In 1308 Giovanni fell into disrepute with the merchant
society of Florence, and was charged with having absconded with
the money and property of others.  Barbi (1925b, pp.  68-69) has
noted a Florentine document proclaiming a sentence "contra Iannem
Buiamontis tanquam contra mercatorem et artificem cessantem et
fugitivum cum pecunia et rebus alienis" ("against Giovanni
Buiamonte as against a merchant or artisan who has absconded and
fled with money and other valuables").

	|73.  tre becchi~: Several of the early commentators say
that the arms of the Becchi family were "on a field or three
goats sable."   The ^Anonimo fiorentino~, for example, remarks:
"Portava per arme il campo giallo et tre becchi neri l'uno sopra
l'altro, come stanno i Leopardi che sono nell'arme del re
d'Inghilterra."  ("His coat of arms consisted of a yellow field
and three goats sable, one above the other, like the leopards on
the escutcheon of the king of England.")

	|74-75.  Qui distorse la bocca...lecchi~: This grotesque
gesture of derision and scorn is directed, not at the wayfarer,
but at the Florentine usurers now in Hell and their "sovereign
knight" who will one day join them.  The gesture is known in
Italian as ^fare le boccacce.~  See Isa. 57:4: "Super quem
lusistis? super quem dilatastis os et eiecistis linguam?" ("Upon
whom have you jested? Upon whom have you opened your mouth wide
and put out your tongue?") / The qualifying phrase, "come bue che
'l naso lecchi," adds a touch of the ^bestialitas~ that
characterizes this seventh circle (see ^Inf.~ XI, 83).

	|76-77.  E io...lui~: For this construction see ^Inf.~
III, 80-81.

	|77.  lui~: Virgil. ^di poco star~: See vs. 40.

	|'mmonito~ = ^ammonito.~

	|78.  torna'mi~ = ^mi tornai.~

	|81-84.  Or sie forte...male~: Porena acutely observes
that Virgil here uses every means to encourage the wayfarer:
example (he himself has "already mounted" Geryon); exhortation
("be strong and bold"); reason (there is no other means of
descent to the eighth circle); protection (he bids Dante climb on
in front of him, so that he, Virgil, is "between" the wayfarer
and the creature's dangerous tail).

	|81.  sie~ = ^sii.~

	|82.  Omai~: "Now," "at this point" in Hell to which we
have come.  The word also suggests "from this point on,"
"henceforward," which is in fact borne out: a giant will set
Virgil and Dante down on the bottommost level of Hell.

	|s@i fatte scale~: Given the context, the metaphor is obviously
ironic, an acknowledgment on Virgil's part, as he exhorts the wayfarer,
that there might indeed have been less frightful "stairs."

	|83.  mezzo~ = ^medio.~  See ^Conv.~ IV, xvii, 7: "E queste
tutte sono li mezzi intra quelli."  ("And they themselves are the
[mean] between them.")

	|85.  riprezzo~ = ^ribrezzo.~

	|85-86.  riprezzo de la quartana~: The shivering fit that
precedes the paroxysm of the quartan fever is intermittent and
recurs in four-day cycles (whence the name).

	|87.  pur guardando~: "At the merest glimpse
of."

	|'l rezzo~ = ^l'orezzo.~  Scartazzini-Vandelli calls
attention to a comment of Vincenzo Borghini on these words.  See
Borghini, "Errori," p. 235: "Chiamasi in Toscana, e credo per
tutto, ^Rezzo~, ove ^non batte sole~, e ^stare al Rezzo~, ove
^non sia sole."~  ("In Tuscany, and I believe everywhere else
too, ^rezzo~ means `a place upon which the sun does not shine';
and ^stare al rezzo~ means `to be where there is no sun.'") See
^Inf.~ XXII, 75.

	|88.  parole porte~: See the expression ^porgere parole~
in ^Inf.~ II, 135; ^Inf.~ V, 108.

	|89-90.  ma vergogna mi f$e...forte~: Shame is here
personified, as if she might shake an admonishing finger at the
servant in the presence of a worthy master.  See ^Conv.~ IV, xix,
8: "e tocca nobilitade, che bene @e vera salute, essere l@a dove
@e vergogna, cioe' tema di disnoranza" ("which refers to
nobleness, which is indeed a truly saving thing -- to exist where
there is sensitiveness to shame, that is, fear of dishonor").

	|92.  s@i volli dir~: "S@i" modifies "volli," and the
whole expression means "I did indeed wish to say."

	|95.  ad altro forse~: "Forse" is treated as a noun here
and can mean "dubious moment" (for example, in the expression
^stare in forse~) or, in this instance, "peril"; see ^Purg.~
XXVII, 22-23, where this moment on Geryon's back is remembered as
one of greatest danger.  Another moment of peril in which Virgil
helped Dante was recorded in ^Inf.~ IX, 58-60, when he shielded
his charge from the Gorgon.  Other readings have been proposed,
however; for example, see M. Barbi (1934a), p. 46, who argues
for ^alto forse.~  Also see the evaluation of this problematical
expression by Petrocchi in his note on this verse.

	|98.  le rote larghe~ = ^le rote siano larghe.~

	|99.  la nova soma~: This most unusual burden of a living
man.

	|100.  di loco~: "From its berth."   The "burchio" (vs.
19) has now become, figuratively, a larger vessel, a small ship.

	|102.  a gioco~: "Free" of encumbrance, "at large."

	|104.  e quella tesa~: Up to now the monster has kept its
tail turned up; see vs. 26.

	|105.  con le branche l'aere a s$e raccolse~: This,
indeed, was the manner in which the monster came swimming upward
from the void, as the image at the end of the preceding canto
suggested; see especially the phrase (^Inf.~ XVI, 136): "che 'n
s@u si stende."

	|107.  Fetonte~: In classical mythology Pha,ethon was the
son of Helios, god of the Sun, and Clymene.  He persuaded Helios
to let him drive the chariot of the Sun for one day; but he was
too weak to hold the horses and they rushed out of their usual
course, approaching so near to Earth that they almost set her on
fire.  Jupiter, then, in answer to the prayer of Earth, killed
Pha,ethon with a thunderbolt and hurled him down into the Po.
Dante alludes to the story, which is elaborated by Ovid (^Metam.~
II. 1-328), more than once in the ^Commedia.~  See, for example,
^Par.~ XVII, 1-3.

	|abbandon@o li freni~: See ^Metam.~ II, 200: "Lora
remisit."  ("Down he dropped the reins.")

	|108.  per che 'l ciel, come pare ancor, si cosse~: This
is a reference to the Milky Way or Galaxy (termed "Galassia" in
^Par.~ XIV, 99).  See ^Conv.~ II, xiv, 56:

     Per che @e da sapere che di quella Galassia li filosofi
     hanno avute diverse oppinioni.  Ch@e li Pittagorici dissero
     che 'l Sole alcuna fiata err@o ne la sua via e, passando per
     altre parti non convenienti al suo fervore, arse lo luogo
     per lo quale pass@o, e rimasevi quella apparenza de
     l'arsura: e credo che si mossero da la favola di Fetonte, la
     quale narra Ovidio nel principio del secondo di
     Metamorfoseos.

     Wherefore we are to know that concerning this milky way
     philosophers have held divers opinions.  For the
     Pythagoreans said that once upon a time the sun strayed in
     his course, and passing through other portions not suited to
     his heat scorched the place along which he passed; and this
     appearance of scorching was left there.  And I believe that
     they were moved thereto by the fable of Pha,eton, which Ovid
     tells in the beginning of the second of the ^Metamorphoses.~

Following this passage, Dante proceeds to discuss more scientific
causes of the phenomenon.

	|109.  Icaro~: Pronounced ^@Icaro.~  Icarus was the son of
Daedalus, the famous artisan. Father and son were attempting to
fly from Crete on wings made by Daedalus, when Icarus fell into
the sea and was drowned.  The story is related by Ovid; see
especially ^Metam.~ VIII, 200-209, 222-35.

	|111.  Mala via tieni!~  The father's cry to his son is
Dante's own invention. In Ovid's story (^Metam.~ VIII, 231-32)
Daedalus calls: "Icare.../ Icare...ubi es? qua te regione
requiram?" ("Icarus, Icarus, where are you? In what place shall I
seek you?")

	|117.  se non che al viso~: The wayfarer knows from the
wind on his face that he is moving through the air and assumes
that Geryon is obeying Virgil's instructions and thus is
wheeling.

	|e di sotto mi venta~: Dante also knows, by the
wind "from below," that he is descending.

	|118.  da la man destra il gorgo~: Geryon, who apparently
is wheeling in a clockwise direction (if viewed from above),
passes the cascade of boiling blood as it crashes into the pool
below, which is now much nearer, since they have already
descended a considerable distance.

	|121.  stoscio~: Some editors have adopted the reading
"scoscio," understanding the meaning to be "in my straddle"; but
Petrocchi agrees with other editors in adopting, on good
manuscript authority, "stoscio," meaning "fall," "descent," which
the present translation follows.  See his note on this vexed
problem.

	|122.  per@o ch'~ = ^perci@o che.~

	|123.  tutto mi raccoscio~: "I press in firmly with my
thighs."

	|124-125.  E vidi poi...lo scendere e 'l girar~: Only now
can the wayfarer ^see~ that Geryon is descending in a spiral;
before he could only ^feel~ this from the wind on him.

	|126.  da diversi canti~: This phrase gives a measure of
the "wheeling" course of the descent.

	|127-136.  Come 'l falcon...come da corda cocca~: The
closing image of Geryon's arrival at the bottom of the abyss and
his swift departure is most striking in its assumption of an
observation post -- assumed before it actually is reached.  In the
first term of the comparison, we are privileged to take up a
position corresponding to that of the falconer, and to watch
Geryon circle about, like a falcon weary from an unsuccessful
hunt, and finally land, "disdegnoso e fello" (vs.  132), at some
distance from this point, which in actuality does not exist.  In
the second term of the simile, Dante, having dismounted, assumes
the position of the falconer, to watch the dragon-like monster
vanish upward, as if it were initiating the flight of the falcon
in the figure just completed.  Geryon departs, like the falcon
that "si move isnello" (vs. 130), soaring up toward some possible
prey.

	|128.  sanza veder logoro~: The falcon is trained not to
descend until it takes its quarry or is called down by the
falconer, who whirls the lure ("logoro") about his head as a
signal to recall it.  The falconer in the simile, therefore, is
dismayed that the hawk should give up the hunt and descend before
it is called down by the lure.(See Fig. 5.)

	|logoro~: The lure was made by fastening two bird's wings to
the end of a thong and baiting it with a piece of meat which the bird
was allowed to eat.

	|Richiamo~, literally, "signal," is sometimes
used as a synonym for ^logoro~ (see ^Inf.~ III, 117).

	|130.  onde si move~: Some editors prefer "onde si
mosse"; see M. Barbi (1934a), pp. 35-36.  The present tense
adopted here, however, really implies the past tense.

	|133.  ne puose~ = ^ci depose.~

